### ISSUE TITLE
The variable type of capacity

### ISSUE THREAD

**Issue by cai-zhi-jie** [liangrj2014/ISPD24_contest#14]
In the cap file, there is a float capacity:
![image](https://github.com/liangrj2014/ISPD24_contest/assets/73417581/8c6de571-a7c9-43c7-9087-e5c51f3012c5)

But in the evaluator, the Gcell takes the capacity as unsigned int:
![image](https://github.com/liangrj2014/ISPD24_contest/assets/73417581/943bcfdf-10f2-40b0-8ea0-a4a790f5ea84)

Is there a contradiction here?

**Comment by cai-zhi-jie** [comment]
Besides, the unsigned type capacity will also lead to 0 capacity when the actual capacity is a float number, which maybe a bug.
![image](https://github.com/liangrj2014/ISPD24_contest/assets/73417581/a2faa477-f6e0-4723-b977-99f6eea6872b)

**Comment by liangrj2014** [comment]
Thanks for pointing out the bugs! We will update the cap files to make sure all the capacity values are ints.

**Comment by profmadden** [comment]
Vias passing through a grid cell take a fractional amount of demand from the borders.  I'd suggest making the capacity in the evaluator a float, so that the cost functions and routing problems could model things like incremental routing (where some routes and via locations are fixed -- resulting in fractional remaining capacity on the routing grid).

**Comment by liangrj2014** [comment]
That's a good point! We will make the capacity in the evaluator a float instead. Thanks for the great suggestion!
